server:
    port: 8080

spring:
    profiles: dev
    data:
        mongodb:
            host: ds045099.mongolab.com
            port: 45099
            databaseName: gina
            user: gina
            pass: gina

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003



# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: com.gina
      domain: com.gina.domain
      restdto: com.gina.web.rest.dto
    watchdir:
      - target/classes
