server:
    port: 8080

spring:
    profiles: prod
    data:
        mongodb:
            host: ds045099.mongolab.com
            port: 45099
            databaseName: gina
            user: gina
            pass: gina

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
